### PR TITLE
Adding Voll Studentby ip address

### PR DESCRIPTION
**Pull request by kcisek**
I didn't check if it works

### CODE REVIEW

**Comment by dvikan** [comment]
My user login did not work on that. Voll student village is not sit?

**Comment by kcisek** [comment]
Yes, you are right, Voll Student by is Frost Eindom, so probably you need my login, we can add it in somehow encrypted mode. I hope also the system of Miele washing-machines and web interface is the same, I don't know how it look like in SiT.

**Comment by dvikan** [comment]
If you trust me, you can send your login to me and I can make it work. Encrypting it not possible because I need in plaintext to make the correct http request.

**Comment by dvikan** [comment]
sry. deleting this repo

**Pull request closed without merging**
